# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: left_arm
  joint_model_group_pose: left_arm_zero
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    - right_bh_j11_joint
    - right_bh_j12_joint
    - right_bh_j22_joint
    - right_bh_j32_joint
    - j1_joint
    - j2_joint
    - j3_joint
    - j4_joint
    - j5_joint
    - j6_joint
    - j7_joint
    - left_bh_j11_joint
    - left_bh_j12_joint
    - left_bh_j22_joint
    - left_bh_j32_joint
    - kinect_v2_base_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: left_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - j1_joint
      - j2_joint
      - j3_joint
      - j4_joint
      - j5_joint
      - j6_joint
      - j7_joint
  - name: right_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6